(*
    Extended Backus-Naur Form for LoveLanguage (LoL)
*)

program     = space_decl, {space_decl};
var_decl    = kw_var, id, ['=', init] '\n';
fun_decl    = kw_fun, id, '(', param_list, ')', ':', '\n', body;
param_list  = "" | id, {',', id};
body        = stmt_list;
class_decl  = kw_class, id, ':', '\n', decl_list;
space_decl  = kw_space, id, ':', '\n', decl_list;
decl_list   = '\t', decl, {'\t', decl};
decl        = var_decl | fun_decl | class_decl | space_decl;

stmt_list   = '\t', stmt, {'\t', stmt};
stmt        = cond_stmt | while_stmt | jump_stmt | expr_stmt | decl_stmt;

cond_stmt   = kw_if, expr, ':', '\n', body, {kw_elif, expr, ':', '\n', body}, [kw_else, ':', '\n', body];

while_stmt  = kw_while, expr, ':', '\n', body;

jump_stmt   = ret_stmt | break_stmt | cont_stmt;

ret_stmt    = kw_ret, [expr], '\n';
break_stmt  = kw_break, '\n';
cont_stmt   = kw_continue, '\n';

decl_stmt   = block_decl;
block_decl  = var_decl | class_decl;

expr_stmt       = kw_pass, '\n' | expr, '\n';
expr            = assign_expr;
assign_expr     = logor_expr, ['=', asssign_expr];
logor_expr      = logand_expr, [kw_or, logor_expr];
logand_expr     = bitor_expr, [kw_and, logand_expr];
bitor_expr	    = bitxor_expr, ['|', bitor_expr];
bitxor_expr	    = bitand_expr, ['^', bitxor_expr];
bitand_expr	    = eqop_expr, ['&', bitand_expr];
eqop_expr	    = relop_expr, ["==" | "!=", eqop_expr];
relop_expr	    = add_expr, ['<' | '>' | "<=" | ">=", relop_expr];
add_expr	    = mult_expr, ['+' | '-', add_expr];
mult_expr	    = prefix_expr, ['*' | '/' | '%', mult_expr];
prefix_expr     = kw_not, prefix_expr | '~', prefix_expr | postfix_expr;
postfix_expr    = primary_expr, {'(' arg_list ')' | '[' expr ']' | ('.' | "::") id};
arg_list        = [expr, {',', expr}];
primary_expr    = literals_expr | id_expr | group_expr;
literals_expr   = number | string | bool | none;
id_expr         = id;
group_expr      = '(', expr, ')';
number          = integer | float;

kw_and      = "and";
kw_break    = "break";
kw_class    = "class";
kw_continue = "continue";
kw_elif     = "elif";
kw_else     = "else";
kw_fun      = "fun";
kw_if       = "if";
kw_not      = "not";
kw_or       = "or";
kw_pass     = "pass";
kw_ret      = "ret";
kw_space    = "space";
kw_var      = "var";
kw_while    = "while";
kw_true     = "true";
kw_false    = "false";
kw_none     = "none";